README.md

Docs: Include an example how to get HTML out. Closes #23
---
Let's make the life a bit easier for people to get HTML out

Include an example how to get the HTML out

---

README.md

Docs: Corrected test script name in the `README.md`.
---
In former name there was a typo, `tests` script does not exist.

Corrected test script name in the README.md

---

.travis.yml
README.md
package.json
scripts/utils/getkarmaconfig.js

Other: Removed the BrowserStack integration from this repository. See ckeditor/ckeditor5#1742.

Removed the BrowserStack integration from this repository

---

package.json
webpack.config.js

update webpack.config to replace UglifyJS with Terser

---

package.json
scripts/test.js
yarn.lock

Other: Bumped Karma test runner to v6.x. Closes #292.
---

Bumped Karma to v6.x

---

demo-react-16/yarn.lock
demo-react-18/yarn.lock

Internal: Updated `yarn.lock` for demo apps.
---

Updated `yarn.lock` for demo apps.

---

src/useMultiRootEditor.tsx
tests/useMultiRootEditor.jsx

Fix: The toolbar element will be rendered correctly after changing the reference (in the rerendering process). Closes #434.
---

Fixed the rerendering issue of the toolbar element in multi-root editor

---

.eslintrc.js
package.json
yarn.lock

Internal: Bumped dependencies.

Bumped dependencies

---

webpack.config.js

Internal: Fixed resolving the peer dependencies.
---

Fixed resolving the peer dependencies

---

package.json
yarn.lock

Internal: Use` "ckeditor5": "alpha"` in `devDependencies`.
---
Related to https://github.com/cksource/ckeditor5-internal/issues/3703.

Internal: Use` "ckeditor5": "alpha"` in `devDependencies`

---

demo-multiroot-react-18/package.json
demo-multiroot-react-18/src/ContextMultiRootEditorDemo.tsx
demo-multiroot-react-18/src/MultiRootEditorDemo.tsx
demo-multiroot-react-18/src/MultiRootEditorRichDemo.tsx
demo-multiroot-react-18/yarn.lock
demo-multiroot-react-19/package.json
demo-multiroot-react-19/src/ContextMultiRootEditorDemo.tsx
demo-multiroot-react-19/src/MultiRootEditorDemo.tsx
demo-multiroot-react-19/src/MultiRootEditorRichDemo.tsx
demo-multiroot-react-19/yarn.lock
demo-react-16/package.json
demo-react-16/src/ContextDemo.tsx
demo-react-16/src/EditorDemo.tsx
demo-react-16/yarn.lock
demo-react-18/package.json
demo-react-18/src/ContextDemo.tsx
demo-react-18/src/EditorDemo.tsx
demo-react-18/yarn.lock
demo-react-19/package.json
demo-react-19/src/ContextDemo.tsx
demo-react-19/src/EditorDemo.tsx
demo-react-19/yarn.lock

Internal: Updated dependencies to address potential vulnerabilities.
---

Updated dependencies

---

package.json
scripts/ci/is-project-ready-to-release.js

Internal: Convert an internal script to ESM style.
---
Related to #498.

Convert an internal script to ESM style

---

CHANGELOG.md
package.json
scripts/changelog.js
scripts/preparepackages.js
scripts/publishpackages.js

Internal: Alpha release (v9.0.0-alpha.0).
---

Alpha release (v9.0.0-alpha.0)

---

README.md
scripts/ci/is-project-ready-to-release.js
scripts/publishpackages.js
scripts/utils/parsearguments.js
yarn.lock

Internal: Support for releasing the repository for prereleases.
---
Part of https://github.com/cksource/ckeditor5-internal/issues/3710.

Support for prereleases released via CI.

---

CHANGELOG.md

Internal: Alpha release (v9.0.0-alpha.1).
---

Internal: Alpha release (v9.0.0-alpha.1)

---

CHANGELOG.md
scripts/changelog.js
scripts/utils/parsearguments.js

Internal: Changelog for v9.0.0.
---

Changelog for v9.0.0

---

package.json
yarn.lock

Internal: Fresh yarn.lock to address an issue with the "ws" package.
---
* See: https://github.com/ckeditor/ckeditor5-react/security/dependabot/82
* See cksource/ckeditor5-internal#3732.
---
```
yarn why ws
yarn why v1.22.19
[1/4] Why do we have the module "ws"...?
[2/4] Initialising dependency graph...
warning Resolution field "string-width@4.1.0" is incompatible with requested version "string-width@^5.1.2"
warning Resolution field "wrap-ansi@7.0.0" is incompatible with requested version "wrap-ansi@^8.1.0"
warning Resolution field "string-width@4.1.0" is incompatible with requested version "string-width@^4.2.3"
warning Resolution field "string-width@4.1.0" is incompatible with requested version "string-width@^4.2.3"
warning Resolution field "wrap-ansi@7.0.0" is incompatible with …
```

Fresh yarn.lock to address an issue with the "ws" package

---

CHANGELOG.md

Minor changes in Changelog to better expose experimental functions.

Adjust changelog

---

CHANGELOG.md

Internal: Changelog for `v9.2.0`.

Release `v9.2.0`

---

.eslintrc.cjs
demos/cdn-multiroot-react/MultiRootEditorRichDemo.tsx
demos/npm-multiroot-react/MultiRootEditorRichDemo.tsx
package.json
src/useMultiRootEditor.tsx
tests/_utils/editor.ts
yarn.lock

Internal: Add `prevent-license-key-leak` eslint rule
---

Internal: Add `prevent-license-key-leak` eslint rule

---

CHANGELOG.md

Changelog for `v9.3.0`

---

CHANGELOG.md

Internal: Changelog for v9.3.1.
---

Changelog for v9.3.1

---

package.json
tests/context/ckeditorcontext.test.tsx
yarn.lock

Internal: Bumped `vitest` and `@vitest/*` to latest version.
---

Bumped `vitest` and `@vitest/*` to latest version

---

CHANGELOG.md

Internal: Changelog for 9.4.0-alpha.0.

Changelog for: `9.4.0-alpha.0`

---

CHANGELOG.md
src/cloud/useCKEditorCloud.tsx
src/cloud/withCKEditorCloud.tsx

Internal: Changelog for `9.4.0`.

Changelog for `9.4.0`

---

CHANGELOG.md

Internal: Changelog for `9.5.0-alpha.0`.

Changelog for `9.5.0-alpha.0`

---

CHANGELOG.md

Internal: Changelog for v9.5.0.
---

Changelog for v9.5.0

---

CHANGELOG.md

Internal: Changelog for `v10.0.0`.
---

Changelog for `v10.0.0`
