- package.json
- scripts/test.js
- scripts/utils/getkarmaconfig.js
Internal: Test environment will be created from a custom script instead of using Karma's CLI. Closes #25.
---
Karma must be called manually because options specified in CLI overwrites its config.
> Replaced running Karma from CLI to a custom script

- scripts/utils/getkarmaconfig.js
Internal: Add current timestamp to project name for builds on BrowserStack. Thanks to that, badges will always show a status of the latest build and its link open the build instead of the first created build. Closes #44.
> Fixed invalid build name for builds on BrowserStack.

- README.md
- package.json
- src/ckeditor.jsx
- tests/39/1.jsx
- tests/ckeditor-integration.jsx
- tests/ckeditor.jsx
Fix: The `<CKEditor>` component will not be updated by React itself. The editor won't freeze if `#data` property was specified as a static string. Closes #75. Closes #78.
> The component will not be updated by React itself

- package.json
- src/ckeditor.jsx
- tests/ckeditor.jsx
This reverts commit a31de76118130eae1ac8ae82c5c02917f996e211, reversing
changes made to 650b9ca41530491809bde7d29c6bfcd13ae68e55.
Internal: Removed option for providing React refs to the editor configuration. Closes https://github.com/ckeditor/ckeditor5-react/issues/72.
---
> Revert "Merge pull request #73 from ckeditor/t/72"

- src/ckeditor.jsx
- tests/ckeditor.jsx
Fix: The `<CKEditor>` component will not update anything if it is not ready. Closes #83.
> Component will not update anything if it is not ready

- package.json
- scripts/utils/getkarmaconfig.js
- webpack.config.js
Other: `<CKEditor>` React component will be distributed in ES6 instead of ES5. Closes #105.
---
Two things:
- I am not sure how to define the merge message.
- Should it be marked as BC?
cc: @Reinmar
> React Component will be distributed as ES6

- README.md
Internal: Remove Gitter badge. Part of ckeditor/ckeditor5#2075
---
Note there was also a stray tailing whitespace character in the README.md it got fixed too.
> Remove Gitter badge

- src/ckeditor.jsx
- tests/ckeditor.jsx
Feature: Introduced support for `onError` callback that is being called if an error occurred during the editor's initialization. Closes #123.
---
Because CKEditor5 does not expose an onError listener in events, for right now all we can expose is a callback for errors thrown when CKEditor5 is initialized in the CKEditor5-React component.
> Add optional onError callback

- src/ckeditor.jsx
- tests/ckeditor.jsx
Feature: Support for [`config.initialData`](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html#member-initialData) in the configuration object when creating the component. When passing the `[data]` property and the `initialData` value in the configuration, the later one will take precedence and a warning message will be logged on the console.
> Support for config.initialData when creating the component

- scripts/utils/getkarmaconfig.js
- src/ckeditor.jsx
- src/ckeditorcontext.jsx
- tests/_utils-tests/context.js
- tests/_utils-tests/turnoffdefaulterrorcatching.js
- tests/_utils/context.js
- tests/_utils/turnoffdefaulterrorcatching.js
- tests/ckeditor-classiceditor.jsx
- tests/ckeditor.jsx
- tests/ckeditorcontext.jsx
- tests/index.jsx
- tests/integrations/ckeditor-classiceditor.jsx
- tests/integrations/ckeditor-editor-data.jsx
- tests/issues/39-frozen browser.jsx
- yarn.lock
Tests: Added the memory leak tests. Closes #227.
Tests: Added additional tests to cover all use-cases. Closes #183.
Tests: Added tests for dev-utils.
Tests: Grouped tests by test scenarios.
---
> Minor improvements for package's components and tests

- src/ckeditorcontext.jsx
- tests/ckeditorcontext.jsx
Fix: Use async/await in CKEditorContext#_destroyContext() to handle context destruction properly. Closes #283.
---
It is not that easy to test, so here is a short guide explaining how to do it:
1. Get the `real-time-collaboration-comments-outside-of-editor-for-react` collaboration sample and replace original `src/sample.js` with [my code](https://gist.github.com/Mgsy/9453453fd8b95ab97bf5ff8ab94d2857).
2. In `src/sample.js` add import path to the local `ckeditor5-react` package.
3. Build and run the sample.
4. Open the dev tools and the network tab.
5. Click the button to create editors.
6. The WebSocket connection should be _pending_.
7. Click the button to destroy editors.
8. The WebSocket connection should be closed.
The better description and GIFs are available in the original issue.
> Use async/await in CKEditorContext#_destroyContext() to fix the destruction process

- .eslintrc.js
- package.json
- tests/_utils/turnoffdefaulterrorcatching.js
- yarn.lock
Internal: Allowed the "license-header" ESLint rule. Fixed broken license headers across the project. See https://github.com/ckeditor/ckeditor5/issues/11468.
> Allowed the "license-header" ESLint rule. Fixed broken license headers across the project

- sample/index-18.html
- src/ckeditor.jsx
- src/ckeditorcontext.jsx
- yarn.lock
Fix: Fixed component double rendering in StrictMode. Closes #294.
---
It looks like this issue exists only in React v18+. React strict mode checks are run in development mode only. They do not impact the production build. For testing purposes we can use the `sample/index.html`.
1. Checkout the `i/294` branch, bump React version in `package.json` for `react` and `react-dom` to `^18.0.0` and install dependencies.
2. Load the development builds for React framework in the `sample/index.html`:
```diff
- <script src="../node_modules/react/umd/react.production.min.js"></script>
- <script src="../node_modules/react-dom/umd/react-dom.production.min.js"></script>
+ <script src="../node_modules/react/umd/react.development.js"></script>
+ <script …
```
> Fixed component double rendering in StrictMode

- sample/index-18-delayed.html
- src/ckeditor.jsx
- tests/ckeditorcontext.jsx
Fix: Fixed the component initialization procedure to enforce cleanup completion before subsequent editor initialization. Closes #321. Closes #338.
Thanks to @corymharper.
---
Base PR: https://github.com/ckeditor/ckeditor5-react/pull/342.
> Fixed the component initialization procedure to enforce cleanup completion before subsequent editor initialization

- src/ckeditor.jsx
- tests/issues/354-destroy-editor-inside-context.jsx
Fix: Fixed destroy process of a single editor instance working within Context. Closes #354.
> Fixed destroy process of a single editor instance working within Context

- sample/index.html
- src/ckeditor.jsx
- src/ckeditorcontext.jsx
- tests/ckeditor.jsx
- tests/ckeditorcontext.jsx
Feature: Added the `watchdogConfig` property that allows defining configuration for the [Watchdog](https://ckeditor.com/docs/ckeditor5/latest/features/watchdog.html) feature. Closes #360.
---
Related docs PR: ckeditor/ckeditor5#13517
> Added `watchdogConfig` property that allows defining configuration for the Watchdog

- scripts/utils/getkarmaconfig.js
Internal: Fixed using `CI` env variable instead of `TRAVIS` in `getBrowsers()`. See #408.
---
> Fixed using `CI` env variable instead of `TRAVIS` in `getBrowsers()`.

- demo-multiroot-react-18/src/App.tsx
- src/ckeditor.tsx
- src/hooks/useEditorEffect.ts
- src/hooks/useInstantEditorEffect.ts
- src/hooks/useInstantEffect.ts
- src/hooks/useRefSafeCallback.ts
- src/lifecycle/LifeCycleEditorSemaphore.ts
- src/lifecycle/LifeCycleElementSemaphore.ts
- src/lifecycle/useLifeCycleSemaphoreSyncRef.tsx
- src/useMultiRootEditor.tsx
- src/utils/defer.ts
- src/utils/mergeRefs.ts
- src/utils/once.ts
- src/utils/overwriteArray.ts
- src/utils/overwriteObject.ts
- src/utils/shallowCompareArrays.ts
- src/utils/uniq.ts
- tests/_utils/defer.js
- tests/_utils/editor.js
- tests/_utils/timeout.js
- tests/_utils/waitFor.js
- tests/ckeditor.jsx
- tests/ckeditorcontext.jsx
- tests/integrations/ckeditor-classiceditor.jsx
- tests/issues/354-destroy-editor-inside-context.jsx
- tests/useMultiRootEditor.jsx
Fix: Add CKEditor component initialize / destroy semaphore to prevent race conditions during fast rerender. Closes https://github.com/ckeditor/ckeditor5-react/issues/442, https://github.com/ckeditor/ckeditor5-react/issues/469, https://github.com/ckeditor/ckeditor5-react/issues/471, https://github.com/ckeditor/ckeditor5-react/issues/476.
---
Probably related to these issues: 
https://github.com/ckeditor/ckeditor5-react/issues/469
https://github.com/ckeditor/ckeditor5-react/issues/409
https://github.com/ckeditor/ckeditor5/issues/15980
https://github.com/ckeditor/ckeditor5-react/issues/442
https://github.com/ckeditor/ckeditor5-react/issues/476
> Quick rerendering causes editor issues

- src/ckeditorcontext.tsx
- src/hooks/useInstantEditorEffect.ts
- src/lifecycle/LifeCycleElementSemaphore.ts
- src/useMultiRootEditor.tsx
- tests/_utils/multirooteditor.ts
- tests/ckeditor.test.tsx
- tests/ckeditorcontext.test.tsx
- tests/hooks/useInstantEditorEffect.test.tsx
- tests/hooks/useInstantEffect.test.tsx
- tests/hooks/useIsMountedRef.test.tsx
- tests/hooks/useRefSafeCallback.test.tsx
- tests/lifecycle/LifeCycleElementSemaphore.test.tsx
- tests/lifecycle/useLifeCycleSemaphoreSyncRef.test.tsx
- tests/useMultiRootEditor.test.tsx
- tests/utils/defer.test.tsx
- tests/utils/mergeRefs.test.tsx
- tests/utils/once.test.tsx
- tests/utils/overwriteArray.test.tsx
- tests/utils/overwriteObject.test.tsx
- tests/utils/shallowCompareArrays.test.tsx
- tests/utils/uid.test.tsx
- tests/utils/uniq.test.tsx
- vite.config.ts
Tests: Restore 100% coverage in whole project after migration to ESM and new test suite. 
---
Previously, our test suite was returning incorrect coverage info. After migration to `vitest` it shows us that we have ~90% coverage percentage. This PR restores coverage to 100%.
> Restore 100% coverage in project after migration to vitest. 

- .eslintrc.cjs
- package.json
- src/useMultiRootEditor.tsx
- tests/hooks/useInstantEditorEffect.test.tsx
- tests/hooks/useInstantEffect.test.tsx
- tests/hooks/useIsMountedRef.test.tsx
- tests/hooks/useRefSafeCallback.test.tsx
- tests/issues/349-destroy-context-and-editor.test.tsx
- tests/lifecycle/useLifeCycleSemaphoreSyncRef.test.tsx
- tests/useMultiRootEditor.test.tsx
- vite.config.ts
- yarn.lock
Tests: Switch tests to run on `React 18` instead of `16`.
Tests: Drop deprecated `@testing-library/react-hooks` testing util, use `@testing-library/react` instead.
Tests: Add missing `act()` calls.
---
Part of https://github.com/ckeditor/ckeditor5-react/pull/490
> Bump react testing library

- vite.config.ts
Fix: Change the global name used in the UMD build from `CKEditor` to `CKEDITOR_REACT` to match the new convention. See ckeditor/ckeditor5#16736.
MINOR BREAKING CHANGE: Change the global name used in the UMD build from `CKEditor` to `CKEDITOR_REACT`.
---
> Change the UMD global name to `CKEDITOR_REACT`

- src/cloud/useCKEditorCloud.tsx
- src/cloud/withCKEditorCloud.tsx
Docs: Add `experimental` jsdoc to `useCKEditorCloud` and `withCKEditorCloud` hooks.
> Add missing `@experimental` jsdoc to `useCKEditorCloud` and `withCKEditorCloud`

- src/useMultiRootEditor.tsx
- tests/useMultiRootEditor.test.tsx
Fix: Update data of roots with modified content only. Closes #534.
---
See #534 for more details. TL;DR:
> This happens because `setData` returned from `useMultiRootEditor` hook, expects all roots to be passed (since it diffs root list enabling to add/remove them) and existing roots are just updated with passed data, even if it's the same. Such update results in each root model data to be wiped out and re-added which is interpreted by revision history as complete data replace (since it works on model operations and does not diff data changes).
This PR slightly modifies the logic to update only the roots which has changed data.
---
I dug a bit in the context of below comment in the code:
> // If any of the roots content has changed, set the editor data.
> // Unfortunately, we cannot set …
> Fix: Update data of roots with modified content only

- src/hooks/useAsyncCallback.ts
- src/hooks/useAsyncValue.ts
- src/hooks/useInstantEffect.ts
- tests/cloud/useCKEditorCloud.test.tsx
- tests/cloud/withCKEditorCloud.test.tsx
- tests/hooks/useAsyncCallback.test.tsx
- tests/hooks/useAsyncValue.test.tsx
- tests/hooks/useInstantEditorEffect.test.tsx
- tests/hooks/useInstantEffect.test.tsx
- tests/hooks/useIsMountedRef.test.tsx
- tests/hooks/useIsUnmountedRef.test.tsx
- tests/hooks/useRefSafeCallback.test.tsx
Fix: Behavior of `useCKEditorCloud` hook is now consistent on `Vite` and `Next` runtimes while changing properties.
Internal: Fix incorrect typings of `useAsyncCallback` and `useAsyncValue` callback arguments types.
Tests: Add missing `cleanup` methods to few tests.
---
It looks like `useRef` behavior is inconsistent across React frameworks, and it is not related to React version itself (at least 18.x one, 19.x is not affected at all).
Let's assume this component that is being rendered in strict mode:
```tsx
const Component = () => {
const ref = useRef(null);
console.info(ref.current);
ref.current = 'test';
return null;
};
```
1. On **Vite** it will print `null` two times.
2. On **Next.js** it will print `null` the first time, and then `test` second time.
It looks like something changed …
> Fix inconsistent behavior of `useAsyncValue` and `useCKEditorCloud` hooks on `Vite` and `Next` runtimes.

- src/useMultiRootEditor.tsx
Fix: Prevent potential crashes of `useMultiRootEditor` during the initialization phase when setting the new state of the multi-root editor with an attached watchdog. Closes https://github.com/ckeditor/ckeditor5-react/issues/542
---
It appears that some of our tests are causing random restarts of the editor. An example of such a restart might occur when setting some data while the component has not fully rendered the entire CKEditor, and the semaphore begins destroying it while running in the watchdog context.
This PR resets the reinitialized editor data to the one defined in the React state (data is defined in the upper scope). This change seems to make our tests more stable and should be harmless.
> Restore restarted watchdog editor with current react state

- demos/cdn-multiroot-react/main.tsx
- demos/cdn-react/main.tsx
- demos/npm-multiroot-react/main.tsx
- demos/npm-react/ContextDemo.tsx
- demos/npm-react/main.tsx
- package.json
- src/context/useInitializedCKEditorsMap.ts
- tests/_utils/editor.ts
- tests/context/useInitializedCKEditorsMap.test.tsx
- vite.config.ts
- yarn.lock
Feature: Call `onChangeInitializedEditors` when `CKEditorContext` starts if there are already initialized editors. Closes https://github.com/ckeditor/ckeditor5-react/issues/552
---
`onChangeInitializedEditors` should be called after mounting of `CKEditorContext` if there is at least one ready editor.
> Call `onChangeInitializedEditors` on startup of `CKEditorContext` if there are ready editors.

- demos/cdn-react/getCKCdnClassicEditor.ts
- package.json
- src/ckeditor.tsx
- src/plugins/ReactIntegrationUsageDataPlugin.ts
- src/plugins/appendAllIntegrationPluginsToConfig.ts
- src/useMultiRootEditor.tsx
- tests/ckeditor.test.tsx
- tests/cloud/useCKEditorCloud.test.tsx
- tests/useMultiRootEditor.test.tsx
- vite-env.d.ts
- vite.config.ts
- yarn.lock
Feature: Align integration to work with self-service for premium features.
---
More details: https://github.com/ckeditor/ckeditor5/issues/17317
> Align integration to work with self-service for premium features.

- tests/useMultiRootEditor.test.tsx
- vite.config.ts
Tests: Add `retry` option to flaky `multiroot` test, extend delay between assertions. 
Tests: Randomize the order of the tests, to prevent incorrect dependencies across tests. 
---
This test tests quite rare scenario when `setData` is being called when editor is not initialized. In theory - it is possible, but I haven't managed to reproduce this in the real world. At this moment, there were no reports about incorrect behavior, so it's safe enough to retry it a few times.
> Add retries to flaky multiroot semaphores tests.

- package.json
- yarn.lock
Internal: Bump integrations common to `2.2.2`.
---
Sync after release: https://github.com/ckeditor/ckeditor5-integrations-common/pull/47
> Bump integrations common to `2.2.2`.

- package.json
- src/ckeditor.tsx
- src/useMultiRootEditor.tsx
- vite.config.ts
- yarn.lock
Fix: `data` prop is no longer unavailable in Next.js related integrations. Closes https://github.com/ckeditor/ckeditor5-react/issues/567
Other: Remove `prop-types` from dependencies of package.
> Bump React 19 version, remove `prop-types` from main component.

- src/ckeditor.tsx
- src/lifecycle/LifeCycleElementSemaphore.ts
- src/useMultiRootEditor.tsx
- tests/ckeditor.test.tsx
- tests/lifecycle/LifeCycleElementSemaphore.test.tsx
Fix: `onError` was not called when `disableWatchdog` was set to `true`. #591 
Fix: `onError` was not called when watchdog initialization failed. #591 
Fix: Editor no longer crashes when the `disable` option is changed during initialization.
Caused by #591
> Fix inconsistent `onError` callback
